# version: '3.8'

# services:
#   db:
#     image: postgres:15-alpine
#     container_name: ecommerce_db
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: secretpassword
#       POSTGRES_DB: ecommerce_db
#     ports:
#       - "5432:5432"
#     restart: unless-stopped